[package]
name = "jp-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.4", features = ["derive"] }
color-eyre = "0.6.5"
crossterm = "0.29.0"
io = "0.0.2"
ratatui = "0.30.2"
reqwest = { version = "0.13.4", features = ["json"] }
serde = { version = "1.0.229", features = ["derive"] }
sqlx = { version = "0.9.0", features = ["runtime-tokio", "sqlite"] }
tokio = { version = "1.53.1", features = ["full"] }

[[bin]]
name = "jp"
path = "src/main.rs"
